
## docker-compose -f local-docker-file/mongo/docker-compose-approval.yml up --build
services:

  approval-service:
    image: approval-service
    ports:
      - "8086:8086"
    build:
      context: ../../approval-service
      dockerfile: Dockerfile
    container_name: approval-service-single
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - approval-mongodb-single
    networks:
      - spring

  approval-mongodb-single:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/approval:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js   # Initialize MongoDB with data from this script
    container_name: approval-mongodb-single
    networks:
      - spring

  approval-mongo-express-single:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=approval-mongodb-single # Corrected to match the MongoDB service name
    container_name: approval-mongo-express-single
    depends_on:
      - approval-mongodb-single # Updated to match the correct service name
    networks:
      - spring

networks:
  spring:
    driver: bridge
