version: '3.9'

services:

  postgres-user-service:
    image: postgres
    ports:
      - "5438:5432"
    container_name: postgres-user-service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/user:/var/lib/postgresql/data
      - ./postgres/init/user/init.sql:/docker-entrypoint-initdb.d/init.sql



  postgres-room-service:
    image: postgres
    ports:
      - "5439:5432"
    container_name: postgres-room-service
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/room:/var/lib/postgresql/data
      - ./postgres/init/room/init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8889:80"
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password


  mongodb-event-service:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment: # read from documentation
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: # preserve and persist data on my hard drive
      - ./data/mongo/events:/data/db   # localhost-hard-drive:virtual-logical-drive( virtual inside containerize environment)
      - ./mongo/init/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb-event-service




  # Our dependent service
  mongo-express-event:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONG0DB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb-event-service:27017/

    container_name: mongo-express-event-service
    depends_on:
      - mongodb-event-service